name: fork

on:
  workflow_dispatch:

jobs:
  mirror:
    name: Fork on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: alexv587/westjourney-oss
          ref: gh-pages
          path: gh-pages
      - name: Run shell
        run: |
          rm gh-pages/*.json
          rm -rf gh-pages/.git
          cp -r .git/. gh-pages/.git
          cd gh-pages/
          git config --global user.email "forker@fake.com"
          git config --global user.name "forker"
          git checkout -b gh-pages
          git add 1*
          git commit -am "1*"
          git push -u origin gh-pages
          git add 2*
          git commit -am "2*"
          git push
          git add 3*
          git commit -am "3*"
          git push
          git add 4*
          git commit -am "4*"
          git push
          git add 5*
          git commit -am "5*"
          git push
          git add 6*
          git commit -am "6*"
          git push
          git add 7*
          git commit -am "7*"
          git push
